name: Bundle Size Report
description: report (summary & PR) bundle size with comparison to master

inputs:
    reportData:
        description: 'The report data to process'
        required: true

runs:
    using: composite
    steps:
        -   name: Process Report
            id: bundle-size-report
            uses: actions/github-script@v7
            env:
                BUNDLE_SIZE_REPORT: ${{ inputs.reportData }}
            with:
                script: |
                    const { default: script } = await import('${{ github.workspace }}/.github/actions/bundle-size-report/index.mjs');
                    return await script({ fetch, github, context, core });

        -   name: Commit Master Bundle Size Report
            id: commit-report
            if: ${{ steps.bundle-size-report.outputs.SAVED_MASTER_REPORT }}
            shell: bash
            run: |
                git config user.email "ci@react-uploady.org"
                git config user.name "Uploady CI"
                git status
                git checkout -b "updated-bundle-size-report-${{ github.run_id }}"
                git commit -a -m "chore: update master bundle size report"
                push origin 'updated-bundle-size-report-${{ github.run_id }}' --set-upstream --force

        -   name: Create PR for Master Bundle Size Report
            if: ${{ steps.commit-report.outputs.committed == 'true' }}
            uses: peter-evans/create-pull-request@v6
            with:
                title: "chore: update master bundle size report"
                body: "Automatic PR for new bundle size report"
                branch: updated-bundle-size-report-${{ github.run_id }}
                base: "refs/heads/master"
                commit-message: "chore: commit new master bundle size report"



#            uses: EndBug/add-and-commit@v9
#            with:
#                add: ${{ steps.bundle-size-report.outputs.SAVED_MASTER_REPORT }}
#                message: "chore: update master bundle size report"
#                push: origin 'updated-bundle-size-report-${{ github.run_id }}' --set-upstream --force
#                new_branch: updated-bundle-size-report-${{ github.run_id }}
#                committer_name: Uploady Bot
#                committer_email: bot@react-uploady.org
